cmd_/usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/div64.o :=  gcc-4.8 -Wp,-MD,/usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/.div64.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/src/linux-headers-3.16.0-4-common/arch/x86/include -Iarch/x86/include/generated  -I/usr/src/linux-headers-3.16.0-4-common/include -Iinclude -I/usr/src/linux-headers-3.16.0-4-common/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/linux-headers-3.16.0-4-common/include/uapi -Iinclude/generated/uapi -include /usr/src/linux-headers-3.16.0-4-common/include/linux/kconfig.h   -I/usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -m64 -mno-mmx -mno-sse -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 -Wframe-larger-than=2048 -fstack-protector -Wno-unused-but-set-variable -fno-var-tracking-assignments -g -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -DLINUX -D_LINUX_ -D__KERNEL__=1 -DSUPPORT_ARRAY -DDBG=0 -DBITS_PER_LONG=64 -DMODVERSIONS -DMODULE  -I/usr/src/linux-headers-3.16.0-4-common/drivers/scsi -Idrivers/scsi   -I/usr/src/rr232x-linux-src-v1.10.patch2/inc/linux   -I/usr/src/rr232x-linux-src-v1.10.patch2/inc   -I/usr/src/rr232x-linux-src-v1.10.patch2/osm/linux  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(div64)"  -D"KBUILD_MODNAME=KBUILD_STR(rr232x)" -c -o /usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/.tmp_div64.o /usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/div64.c

source_/usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/div64.o := /usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/div64.c

deps_/usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/div64.o := \

/usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/div64.o: $(deps_/usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/div64.o)

$(deps_/usr/src/rr232x-linux-src-v1.10.patch2/product/rr232x/linux/.build/div64.o):
